services:

  mysql:
    image: mysql:8.0
    container_name: mysql-gpustore
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    networks:
      - gpustore-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 10s
      timeout: 5s
      retries: 10

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "9094:9094"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bd_auth?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - gpustore-net

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "9091:9091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bd_usuario?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - gpustore-net

  producto-service:
    build: ./producto-service
    container_name: producto-service
    ports:
      - "9093:9093"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bd_producto?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - gpustore-net

  orden-service:
    build: ./orden-service
    container_name: orden-service
    ports:
      - "9095:9095"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bd_orden?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - gpustore-net

  pago-service:
    build: ./pago-service
    container_name: pago-service
    ports:
      - "9096:9096"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bd_pago?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      ORDEN_SERVICE_URL: http://orden-service:9095
    depends_on:
      mysql:
        condition: service_healthy
      orden-service:
        condition: service_started
    networks:
      - gpustore-net

  envio-service:
    build: ./envio-service
    container_name: envio-service
    ports:
      - "9099:9099"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bd_envio?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      ORDEN_SERVICE_URL: http://orden-service:9095
    depends_on:
      mysql:
        condition: service_healthy
      orden-service:
        condition: service_started
    networks:
      - gpustore-net

  boleta-service:
    build: ./boleta-service
    container_name: boleta-service
    ports:
      - "9098:9098"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bd_boleta?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      USUARIO_SERVICE_URL: http://user-service:9091
      ORDEN_SERVICE_URL: http://orden-service:9095
    depends_on:
      mysql:
        condition: service_healthy
      user-service:
        condition: service_started
      orden-service:
        condition: service_started
    networks:
      - gpustore-net

  resena-service:
    build: ./resena-service
    container_name: resena-service
    ports:
      - "9097:9097"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bd_resena?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      USUARIO_SERVICE_URL: http://user-service:9091
      PRODUCTO_SERVICE_URL: http://producto-service:9093
    depends_on:
      mysql:
        condition: service_healthy
      user-service:
        condition: service_started
      producto-service:
        condition: service_started
    networks:
      - gpustore-net

  soporte-service:
    build: ./soporte-service
    container_name: soporte-service
    ports:
      - "9100:9100"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bd_soporte?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      USUARIO_SERVICE_URL: http://user-service:9091
      ORDEN_SERVICE_URL: http://orden-service:9095
    depends_on:
      mysql:
        condition: service_healthy
      user-service:
        condition: service_started
      orden-service:
        condition: service_started
    networks:
      - gpustore-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "9090:9090"
    environment:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_SECRET_KEY: esta_es_mi_compleja_clave_secreta

      SPRING_CLOUD_GATEWAY_ROUTES_0_URI: http://auth-service:9094
      SPRING_CLOUD_GATEWAY_ROUTES_1_URI: http://user-service:9091
      SPRING_CLOUD_GATEWAY_ROUTES_2_URI: http://carrito-service:9092
      SPRING_CLOUD_GATEWAY_ROUTES_3_URI: http://producto-service:9093
      SPRING_CLOUD_GATEWAY_ROUTES_4_URI: http://producto-service:9093
      SPRING_CLOUD_GATEWAY_ROUTES_5_URI: http://orden-service:9095
      SPRING_CLOUD_GATEWAY_ROUTES_6_URI: http://pago-service:9096
      SPRING_CLOUD_GATEWAY_ROUTES_7_URI: http://resena-service:9097
      SPRING_CLOUD_GATEWAY_ROUTES_8_URI: http://boleta-service:9098
      SPRING_CLOUD_GATEWAY_ROUTES_9_URI: http://envio-service:9099
      SPRING_CLOUD_GATEWAY_ROUTES_10_URI: http://soporte-service:9100
    depends_on:
      - auth-service
      - user-service
      - producto-service
      - orden-service
      - pago-service
      - envio-service
      - boleta-service
      - resena-service
      - soporte-service
    networks:
      - gpustore-net

networks:
  gpustore-net:
    driver: bridge