server:
  port: 9090

spring:
  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: esta_es_mi_compleja_clave_secreta

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: http://localhost:9094
          predicates:
            - Path=/auth/**

        - id: usuario-service
          uri: http://localhost:9091
          predicates:
            - Path=/usuarios/**

        - id: carrito-service
          uri: http://localhost:9092
          predicates:
            - Path=/carritos/**

        - id: producto-service-categorias
          uri: http://localhost:9093
          predicates:
            - Path=/categorias/**

        - id: producto-service-gpus
          uri: http://localhost:9093
          predicates:
            - Path=/gpus/**

        - id: orden-service
          uri: http://localhost:9095
          predicates:
            - Path=/ordenes/**

        - id: pago-service
          uri: http://localhost:9096
          predicates:
            - Path=/pagos/**

        - id: resena-service
          uri: http://localhost:9097
          predicates:
            - Path=/resenas/**

        - id: boleta-service
          uri: http://localhost:9098
          predicates:
            - Path=/boletas/**