server:
  port: ${SERVER_PORT:9096}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

orden:
  service:
    url: ${ORDEN_SERVICE_URL}