server:
  port: ${SERVER_PORT:9099}

spring:
  application:
    name: envio-service

  profiles:
    active: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/bd_envio?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

orden:
  service:
    url: ${ORDEN_SERVICE_URL:http://localhost:9095}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs